project_id = "mvndmnkgtoygsvesktgw"

[functions.escalate-tickets]
verify_jwt = false

[functions.support-create-ticket]
verify_jwt = true

[functions.create-payme-payment]
verify_jwt = true

[functions.create-click-payment]
verify_jwt = true

[functions.create-uzum-payment]
verify_jwt = true

[functions.backfill-districts]
verify_jwt = true

[functions.env-check]
verify_jwt = false

[functions.ai-property-search]
verify_jwt = false
