// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvndmnkgtoygsvesktgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12bmRtbmtndG95Z3N2ZXNrdGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjM3NDQsImV4cCI6MjA2OTUzOTc0NH0.vNCyFA9lp631y7-lz8GJHA1r-HmL7fO2eRc4a5nfU28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});